// === BASE DE DATOS DE MONISTER (versión oficial) ===
// Limpiada y deduplicada. Campos: artist, title, year.
// OJO: los años los revisaremos a fondo (ver mensaje).
const SONGS = [
  { artist: "David Bowie", title: "Starman", year: 1972 },
  { artist: "Rosario", title: "Mi Gato", year: 1992 },
  { artist: "50 Cent", title: "In Da Club", year: 2002 },
  { artist: "Bombai", title: "Solo Si Es Contigo", year: 2017 },
  { artist: "Blondie", title: "Call Me", year: 1980 },
  { artist: "a-ha", title: "Take on Me", year: 1984 },
  { artist: "Smash Mouth", title: "All Star", year: 1997 },
  { artist: "Martin Solveig", title: "Hello", year: 2011 },
  { artist: "One Direction", title: "Story of My Life", year: 2013 },
  { artist: "Eagles", title: "Hotel California", year: 1976 },
  { artist: "Julieta Venegas", title: "Me Voy", year: 2006 },
  { artist: "Mabel", title: "Don't Call Me Up", year: 2019 },
  { artist: "M People", title: "Moving on Up", year: 1993 },
  { artist: "Harry Styles", title: "As It Was", year: 2022 },
  { artist: "Pretenders", title: "Don't Get Me Wrong", year: 1986 },
  { artist: "Efecto Pasillo", title: "Pan y mantequilla", year: 2012 },
  { artist: "Fito y Fitipaldis", title: "Soldadito marinero", year: 2004 },
  { artist: "New Kids On The Block", title: "Step by Step", year: 1990 },
  { artist: "Europe", title: "The Final Countdown", year: 1986 },
  { artist: "Rosa López", title: "Europe's Living A Celebration", year: 2002 },
  { artist: "Alicia Keys", title: "Girl on Fire", year: 2012 },
  { artist: "ROSALÍA", title: "DESPECHÁ", year: 2022 },
  { artist: "The Strokes", title: "Last Nite", year: 2000 },
  { artist: "Eurythmics", title: "Sweet Dreams (Are Made of This)", year: 1982 },
  { artist: "Shakira", title: "La Tortura", year: 2005 },
  { artist: "Spin Doctors", title: "Two Princes", year: 1991 },
  { artist: "Luz Casal", title: "Rufino", year: 1999 },
  { artist: "Fairground Attraction", title: "Perfect", year: 1988 },
  { artist: "Zucchero", title: "Baila (Sexy Thing)", year: 2001 },
  { artist: "Coldplay", title: "Viva La Vida", year: 2008 },
  { artist: "MAGIC!", title: "Rude", year: 2013 },
  { artist: "Snow Patrol", title: "Chasing Cars", year: 2005 },
  { artist: "Sheryl Crow", title: "All I Wanna Do", year: 1993 },
  { artist: "Vengaboys", title: "Boom, Boom, Boom, Boom!!", year: 1998 },
  { artist: "Alaska Y Dinarama", title: "A quién le importa", year: 1986 },
  { artist: "Roberto Carlos", title: "El Gato Que Está Triste y Azul", year: 1972 },
  { artist: "Rita Ora", title: "Anywhere", year: 2017 },
  { artist: "Eros Ramazzotti", title: "La Cosa Mas Bella", year: 1996 },
  { artist: "Madness", title: "Our House", year: 1982 },
  { artist: "Hues Corporation", title: "Rock the Boat", year: 1975 },
  { artist: "The Kid LAROI", title: "STAY", year: 2022 },
  { artist: "Taylor Swift", title: "Shake It Off", year: 2014 },
  { artist: "Andy & Lucas", title: "Son de Amores", year: 2003 },
  { artist: "Bomba Estéreo", title: "Soy Yo", year: 2015 },
  { artist: "Dolores Vargas", title: "Achilipú", year: 1970 },
  { artist: "Blur", title: "Song 2", year: 1997 },
  { artist: "Chenoa", title: "Cuando Tú Vas", year: 2002 },
  { artist: "The Offspring", title: "Self Esteem", year: 1994 },
  { artist: "Jawsh 685", title: "Savage Love (Laxed - Siren Beat)", year: 2020 },
  { artist: "U2", title: "Vertigo", year: 2002 },
  { artist: "Tracy Chapman", title: "Fast Car", year: 1988 },
  { artist: "Camela", title: "Cuando zarpa el amor", year: 2004 },
  { artist: "Scatman John", title: "Scatman (ski-ba-bop-ba-dop-bop)", year: 1994 },
  { artist: "Natasha Bedingfield", title: "Unwritten", year: 2004 },
  { artist: "Pecos", title: "Háblame de Ti", year: 1979 },
  { artist: "Roxette", title: "Sleeping In My Car", year: 1993 },
  { artist: "Toni Braxton", title: "Un-Break My Heart", year: 1996 },
  { artist: "José de Rico", title: "Rayos de Sol", year: 2011 },
  { artist: "Michael Jackson", title: "Billie Jean", year: 1982 },
  { artist: "Gloria Estefan", title: "Oye", year: 1998 },
  { artist: "Evanescence", title: "Bring Me To Life", year: 2002 },
  { artist: "Ultra Naté", title: "Free", year: 1997 },
  { artist: "The Pointer Sisters", title: "I'm So Excited", year: 1982 },
  { artist: "Green Day", title: "American Idiot", year: 2004 },
  { artist: "Joaquín Sabina", title: "19 Dias y 500 Noches", year: 2020 },
  { artist: "Gala", title: "Freed From Desire", year: 1996 },
  { artist: "COZ", title: "Las Chicas Son Guerreras", year: 1980 },
  { artist: "Hombres G", title: "Suéltate el pelo", year: 1988 },
  { artist: "The Human League", title: "Don't You Want Me", year: 1981 },
  { artist: "KISS", title: "I Was Made For Lovin' You", year: 1979 },
  { artist: "Deee-Lite", title: "Groove Is in the Heart", year: 1990 },
  { artist: "Lipps Inc.", title: "Funkytown", year: 1980 },
  { artist: "Pino D'Angiò", title: "Ma quale idea", year: 1980 },
  { artist: "No Me Pises Que Llevo Chanclas", title: "El Canario", year: 1994 },
  { artist: "Ole Ole", title: "Sola (Con un desconocido)", year: 2001 },
  { artist: "Los Rebeldes", title: "Mediterraneo", year: 1986 },
  { artist: "The Jackson 5", title: "ABC", year: 1970 },
  { artist: "Bon Jovi", title: "Livin' On A Prayer", year: 1986 },
  { artist: "Culture Beat", title: "Mr. Vain", year: 1993 },
  { artist: "MC Hammer", title: "U Can't Touch This", year: 1990 },
  { artist: "Luis Miguel", title: "Suave", year: 1993 },
  { artist: "Farruko", title: "Pepas", year: 2021 },
  { artist: "Phil Collins", title: "Another Day in Paradise", year: 1989 },
  { artist: "Eric Carmen", title: "All By Myself", year: 1975 },
  { artist: "Mike Oldfield", title: "Moonlight Shadow", year: 1983 },
  { artist: "P!nk", title: "Try", year: 2012 },
  { artist: "Chicory Tip", title: "Son Of My Father", year: 1972 },
  { artist: "Justin Bieber", title: "Baby", year: 2010 },
  { artist: "Melody", title: "El Baile del Gorila", year: 2000 },
  { artist: "Adele", title: "Hello", year: 2015 },
  { artist: "The Beatles", title: "Let It Be", year: 1969 },
  { artist: "Isabel Pantoja", title: "Se Me Enamora el Alma", year: 1989 },
  { artist: "T. Rex", title: "Get It On", year: 1971 },
  { artist: "Alanis Morissette", title: "Ironic", year: 1995 },
  { artist: "Love of Lesbian", title: "Fantastic Shine", year: 2013 },
  { artist: "KAROL G", title: "Tusa", year: 2019 },
  { artist: "Leiva", title: "Sincericidio", year: 2016 },
  { artist: "Rudimental", title: "These Days", year: 2018 },
  { artist: "Jonas Brothers", title: "Sucker", year: 2019 },
  { artist: "Marshmello", title: "FRIENDS", year: 2018 },
  { artist: "Lola Indigo", title: "Ya No Quiero Ná", year: 2022 },
  { artist: "Orquesta Mondragon", title: "Viaje con nosotros", year: 1980 },
  { artist: "Stevie Wonder", title: "Part-Time Lover", year: 1985 },
  { artist: "Benny Benassi", title: "Satisfaction", year: 2002 },
  { artist: "t.A.T.u.", title: "All The Things She Said", year: 2002 },
  { artist: "Sophie Ellis-Bextor", title: "Murder On The Dancefloor", year: 2002 },
  { artist: "Malú", title: "Blanco y Negro", year: 2010 },
  { artist: "Justin Timberlake", title: "CAN'T STOP THE FEELING!", year: 2016 },
  { artist: "Nil Moliner", title: "Mi Religión", year: 2020 },
  { artist: "Anastacia", title: "I'm Outta Love", year: 2000 },
  { artist: "Ricky Martin", title: "La Mordidita", year: 2015 },
  { artist: "KC & The Sunshine Band", title: "That's the Way (I Like It)", year: 1975 },
  { artist: "The Communards", title: "Don't Leave Me This Way", year: 1986 },
  { artist: "Prince", title: "Purple Rain", year: 1987 },
  { artist: "Luis Aguile", title: "La vida pasa felizmente", year: 2002 },
  { artist: "will.i.am", title: "Scream & Shout", year: 2012 },
  { artist: "Ryan Paris", title: "Dolce Vita", year: 1983 },
  { artist: "Lionel Richie", title: "All Night Long (All Night)", year: 1983 },
  { artist: "Proyecto Uno", title: "Tiburon", year: 1993 },
  { artist: "Pedro Marin", title: "Aire", year: 1980 },
  { artist: "Felix Jaehn", title: "Ain't Nobody (Loves Me Better)", year: 2016 },
  { artist: "Robbie Williams", title: "Rock DJ", year: 2000 },
  { artist: "James Blunt", title: "You're Beautiful", year: 2004 },
  { artist: "Black Eyed Peas", title: "I Gotta Feeling", year: 2009 },
  { artist: "Village People", title: "YMCA", year: 1978 },
  { artist: "Paloma San Basilio", title: "Juntos", year: 1981 },
  { artist: "USHER", title: "Yeah!", year: 2004 },
  { artist: "Rick Astley", title: "Never Gonna Give You Up", year: 1987 },
  { artist: "John Travolta", title: "Greased Lighten'", year: 1978 },
  { artist: "Georgie Dann", title: "Bimbó 92", year: 1995 },
  { artist: "Rebeca", title: "Duro De Pelar", year: 1996 },
  { artist: "Micky", title: "Enseñame a Cantar", year: 2016 },
  { artist: "Jennifer Lopez", title: "Una Noche Más", year: 1999 },
  { artist: "Avril Lavigne", title: "Complicated", year: 2002 },
  { artist: "Orchestral Manoeuvres In The Dark", title: "Enola Gay", year: 1980 },
  { artist: "David Civera", title: "Que La Detengan", year: 2002 },
  { artist: "24kGoldn", title: "Mood", year: 2020 },
  { artist: "The Pussycat Dolls", title: "Don't Cha", year: 2005 },
  { artist: "Robert Palmer", title: "Simply Irresistible", year: 1988 },
  { artist: "Bodyrockers", title: "I Like The Way", year: 2004 },
  { artist: "Duncan Dhu", title: "Cien gaviotas", year: 1986 },
  { artist: "Bizarrap", title: "Quevedo: Bzrp Music Sessions, Vol. 52/66", year: 2022 },
  { artist: "Leona Lewis", title: "Bleeding Love", year: 2007 },
  { artist: "Becky G", title: "Mayores", year: 2017 },
  { artist: "Nek", title: "Laura no està", year: 1997 },
  { artist: "Thalia", title: "Arrasando", year: 2000 },
  { artist: "Inner Circle", title: "Sweat (A La La La La Long)", year: 1992 },
  { artist: "Juan Luis Guerra 4.40", title: "La Bilirrubina", year: 1990 },
  { artist: "Chimo Bayo", title: "Asi Me Gusta a Mi", year: 1991 },
  { artist: "Los Manolos", title: "Amigos para Siempre", year: 1992 },
  { artist: "Extremoduro", title: "Salir", year: 1998 },
  { artist: "Madonna", title: "Hung Up", year: 2005 },
  { artist: "Iggy Pop", title: "The Passenger", year: 1977 },
  { artist: "Bryan Adams", title: "The Only Thing That Looks Good On Me Is You", year: 1996 },
  { artist: "Bobby McFerrin", title: "Don't Worry Be Happy", year: 1988 },
  { artist: "ABBA", title: "Mamma Mia", year: 1975 },
  { artist: "Shawn Mendes", title: "There's Nothing Holdin' Me Back", year: 2016 },
  { artist: "Maluma", title: "Hawái", year: 2020 },
  { artist: "Meredith Brooks", title: "Bitch", year: 1997 },
  { artist: "The Weeknd", title: "Save Your Tears", year: 2019 },
  { artist: "Sabrina", title: "Boys", year: 1988 },
  { artist: "La Unión", title: "Lobo-hombre en París", year: 1984 },
  { artist: "Cyndi Lauper", title: "Girls Just Want to Have Fun", year: 1983 },
  { artist: "Desireless", title: "Voyage voyage", year: 1986 },
  { artist: "Nick Kamen", title: "I Promised Myself", year: 1990 },
  { artist: "Paco Pil", title: "Johnny Techno Ska", year: 1994 },
  { artist: "Pedro Capó", title: "Calma", year: 2018 },
  { artist: "fun.", title: "We Are Young", year: 2012 },
  { artist: "María Isabel", title: "Antes Muerta Que Sencilla", year: 2004 },
  { artist: "Crystal Waters", title: "Gypsy Woman (She's Homeless) (La Da Dee La Da Da)", year: 1991 },
  { artist: "iNi Kamoze", title: "Here Comes the Hotstepper", year: 1994 },
  { artist: "Miami Sound Machine", title: "Conga!", year: 1985 },
  { artist: "Kate Ryan", title: "Ella Elle L A", year: 2008 },
  { artist: "Pet Shop Boys", title: "It's a Sin", year: 1987 },
  { artist: "Dover", title: "Let Me Out", year: 2006 },
  { artist: "Clean Bandit", title: "Rockabye", year: 2017 },
  { artist: "Sonia Y Selena", title: "Yo Quiero Bailar", year: 2001 },
  { artist: "Sean Kingston", title: "Beautiful Girls", year: 2007 },
  { artist: "Whigfield", title: "Saturday Night", year: 1993 },
  { artist: "Chayanne", title: "Madre Tierra (Oye)", year: 2014 },
  { artist: "Jeanette", title: "¿Porqué te vas?", year: 1974 },
  { artist: "Drake", title: "One Dance", year: 2016 },
  { artist: "zzoilo", title: "Mon Amour", year: 2021 },
  { artist: "George Ezra", title: "Budapest", year: 2013 },
  { artist: "Ella Baila Sola", title: "Lo echamos a suertes", year: 1996 },
  { artist: "Miguel Ríos", title: "Bienvenidos", year: 1982 },
  { artist: "Ana Belén", title: "Agapimu", year: 1979 },
  { artist: "Patti Smith", title: "Because the Night", year: 1978 },
  { artist: "Green Day", title: "Basket Case", year: 1993 },
  { artist: "Michel Teló", title: "Ai Se Eu Te Pego", year: 2011 },
  { artist: "Don McLean", title: "American Pie", year: 1971 },
  { artist: "Kylie Minogue", title: "Can't Get You out of My Head", year: 2001 },
  { artist: "Stars On 45", title: "Stars On 45", year: 1981 },
  { artist: "Avicii", title: "Wake Me Up", year: 2013 },
  { artist: "Jessie J", title: "Price Tag", year: 2011 },
  { artist: "The B-52's", title: "Love Shack", year: 1989 },
  { artist: "Radiohead", title: "Creep", year: 1992 },
  { artist: "Yves Larock", title: "Rise Up", year: 2007 },
  { artist: "Chumbawamba", title: "Tubthumping", year: 1997 },
  { artist: "Måneskin", title: "I WANNA BE YOUR SLAVE", year: 2021 },
  { artist: "*NSYNC", title: "Bye Bye Bye", year: 2000 },
  { artist: "The White Stripes", title: "Seven Nation Army", year: 2003 },
  { artist: "Right Said Fred", title: "I'm Too Sexy", year: 1991 },
  { artist: "Franz Ferdinand", title: "Do You Want To", year: 2005 },
  { artist: "Take That", title: "Back for Good", year: 1994 },
  { artist: "Counting Crows", title: "Mr. Jones", year: 1991 },
  { artist: "Lizzo", title: "About Damn Time", year: 2022 },
  { artist: "Donna Summer", title: "Hot Stuff", year: 1979 },
  { artist: "Jamiroquai", title: "Little L", year: 2001 },
  { artist: "U.S.A. For Africa", title: "We Are The World", year: 1985 },
  { artist: "El Sueño de Morfeo", title: "Nunca volverá", year: 2005 },
  { artist: "Wham!", title: "Wake Me Up Before You Go-Go", year: 1984 },
  { artist: "Beyoncé", title: "Single Ladies (Put a Ring on It)", year: 2008 },
  { artist: "Kesha", title: "TiK ToK", year: 2010 },
  { artist: "Los Chichos", title: "Ni Mas Ni Menos", year: 2003 },
  { artist: "Texas", title: "I Don't Want A Lover", year: 1989 },
  { artist: "Vicente Fernández", title: "Volver, Volver", year: 1979 },
  { artist: "Technotronic", title: "Pump Up The Jam", year: 1989 },
  { artist: "Backstreet Boys", title: "Everybody (Backstreet's Back)", year: 1997 },
  { artist: "Ava Max", title: "Kings & Queens", year: 2020 },
  { artist: "Roxy Music", title: "More Than This", year: 1982 },
  { artist: "Bee Gees", title: "Stayin Alive", year: 1977 },
  { artist: "Hanson", title: "MMMBop", year: 1996 },
  { artist: "Rodolfo Chikilicuatre", title: "Baila el Chiki Chiki", year: 2008 },
  { artist: "B.o.B", title: "Airplanes", year: 2010 },
  { artist: "Doja Cat", title: "Kiss Me More", year: 2021 },
  { artist: "Coyote Dax", title: "No Rompas Mi Corazón", year: 2001 },
  { artist: "OBK", title: "Historias de amor", year: 1991 },
  { artist: "Peret", title: "Borriquito", year: 1972 },
  { artist: "Mari Trini", title: "Yo no soy esa", year: 1971 },
  { artist: "Calvin Harris", title: "Summer", year: 2014 },
  { artist: "Modjo", title: "Lady", year: 2000 },
  { artist: "The Killers", title: "Human", year: 2008 },
  { artist: "Julia Michaels", title: "Issues", year: 2017 },
  { artist: "The Rubettes", title: "Sugar Baby Love", year: 1974 },
  { artist: "Radio Futura", title: "Escuela de Calor", year: 1983 },
  { artist: "Spice Girls", title: "Wannabe", year: 1996 },
  { artist: "Scissor Sisters", title: "I Don't Feel Like Dancin'", year: 2006 },
  { artist: "Carlinhos Brown", title: "María Caipirinha", year: 2004 },
  { artist: "George Michael", title: "Faith", year: 1987 },
  { artist: "Eiffel 65", title: "Blue (Da Ba Dee)", year: 1999 },
  { artist: "Will Smith", title: "Gettin' Jiggy Wit It", year: 1997 },
  { artist: "Conchita", title: "Nada Que Perder", year: 2007 },
  { artist: "The Rolling Stones", title: "Angie", year: 1973 },
  { artist: "Juan Magán", title: "Bailando por Ahi", year: 2001 },
  { artist: "BTS", title: "Dynamite", year: 2020 },
  { artist: "Sandro Giacobbe", title: "El Jardín Prohibido", year: 1979 },
  { artist: "Camilo", title: "Vida de Rico", year: 2020 },
  { artist: "Aerosmith", title: "Cryin'", year: 1993 },
  { artist: "Alexandra Stan", title: "Mr. Saxobeat", year: 2011 },
  { artist: "Jonas Blue", title: "Perfect Strangers", year: 2016 },
  { artist: "Rauw Alejandro", title: "Todo De Ti", year: 2021 },
  { artist: "Ramones", title: "Blitzkrieg Bop", year: 1976 },
  { artist: "Survivor", title: "Eye of the Tiger", year: 1982 },
  { artist: "The Corrs", title: "What Can I Do", year: 1997 },
  { artist: "Michael Jackson", title: "Scream", year: 1995 },
  { artist: "Christina Aguilera", title: "Beautiful", year: 2002 },
  { artist: "Jessie J", title: "Bang Bang", year: 2014 },
  { artist: "Queen", title: "Another One Bites The Dust", year: 1980 },
  { artist: "Christie", title: "Yellow River", year: 1970 },
  { artist: "Gnarls Barkley", title: "Crazy", year: 2006 },
  { artist: "Bonnie Tyler", title: "Holding Out for a Hero", year: 1984 },
  { artist: "Eminem", title: "Stan", year: 2005 },
  { artist: "Yolanda Be Cool", title: "We No Speak Americano (Edit)", year: 2010 },
  { artist: "La Quinta Estacion", title: "Que Te Quería", year: 2009 },
  { artist: "TLC", title: "No Scrubs", year: 1999 },
  { artist: "Café Quijano", title: "La Lola", year: 1999 },
  { artist: "Pitbull", title: "I Know You Want Me (Calle Ocho)", year: 2007 },
  { artist: "Depeche Mode", title: "Just Can't Get Enough", year: 1981 },
  { artist: "Lady Gaga", title: "Bad Romance", year: 2009 },
  { artist: "Sia", title: "Chandelier", year: 2014 },
  { artist: "Gwen Stefani", title: "What You Waiting For?", year: 2004 },
  { artist: "Celtas Cortos", title: "Cuéntame un cuento", year: 1991 },
  { artist: "Rod Stewart", title: "Da Ya Think I'm Sexy?", year: 1978 },
  { artist: "Fuego", title: "Una Vaina Loca", year: 2011 },
  { artist: "Ellie Goulding", title: "Love Me Like You Do", year: 2015 },
  { artist: "Black Eyed Peas", title: "Where Is The Love?", year: 2003 },
  { artist: "The Weather Girls", title: "It's Raining Men", year: 1982 },
  { artist: "Fatboy Slim", title: "The Rockafeller Skank", year: 1998 },
  { artist: "Taio Cruz", title: "Dynamite", year: 2010 },
  { artist: "Belinda Carlisle", title: "Heaven Is A Place On Earth", year: 1987 },
  { artist: "The Chemical Brothers", title: "Hey Boy Hey Girl", year: 1999 },
  { artist: "Ariana Grande", title: "7 rings", year: 2019 },
  { artist: "George McCrae", title: "Rock Your Baby", year: 1974 },
  { artist: "John Paul Young", title: "Love Is In The Air", year: 1977 },
  { artist: "Des'ree", title: "Life", year: 1998 },
  { artist: "Beret", title: "Lo siento", year: 2018 },
  { artist: "Flo Rida", title: "Whistle", year: 2012 },
  { artist: "Dani Martín", title: "Cero", year: 2013 },
  { artist: "Charlie Puth", title: "We Don't Talk Anymore", year: 2016 },
  { artist: "Alphaville", title: "Forever Young", year: 1984 },
  { artist: "SNAP!", title: "The Power", year: 1990 },
  { artist: "Loco Mía", title: "Locomia", year: 2016 },
  { artist: "David Guetta", title: "Titanium", year: 2012 },
  { artist: "House Of Pain", title: "Jump Around", year: 1992 },
  { artist: "Chocolate", title: "Mayonesa", year: 2001 },
  { artist: "Los Ronaldos", title: "No Puedo Vivir Sin Ti", year: 2007 },
  { artist: "Nino Bravo", title: "América, América", year: 1973 },
  { artist: "Juanes", title: "Me Enamora", year: 2007 },
  { artist: "Edward Maya", title: "Stereo Love", year: 2009 },
  { artist: "Elton John", title: "Don't Go Breaking My Heart", year: 1993 },
  { artist: "Rihanna", title: "Umbrella", year: 2007 },
  { artist: "R.E.M.", title: "Losing My Religion", year: 1991 },
  { artist: "El Canto Del Loco", title: "Peter Pan", year: 2008 },
  { artist: "Portugal. The Man", title: "Feel It Still", year: 2017 },
  { artist: "Moby", title: "Escapar (Slipping Away)", year: 2005 },
  { artist: "Imagine Dragons", title: "Believer", year: 2017 },
  { artist: "Mark Ronson", title: "Uptown Funk", year: 2015 },
  { artist: "Desmadre 75", title: "Saca el guisky cheli", year: 1975 },
  { artist: "Guns N' Roses", title: "Sweet Child O' Mine", year: 1987 },
  { artist: "Queen", title: "Under Pressure", year: 1982 },
  { artist: "Duo Dinamico", title: "Quisiera ser", year: 1987 },
  { artist: "Morat", title: "Cómo Te Atreves", year: 2016 },
  { artist: "AronChupa", title: "I'm an Albatraoz", year: 2014 },
  { artist: "Nelly", title: "Dilemma", year: 2002 },
  { artist: "Sinéad O'Connor", title: "Nothing Compares 2 U", year: 1990 },
  { artist: "Vanilla Ice", title: "Ice Ice Baby", year: 1990 },
  { artist: "Lolita", title: "Amor, Amor", year: 2013 },
  { artist: "Joe Cocker", title: "With A Little Help From My Friends", year: 1969 },
  { artist: "Kaoma", title: "Lambada", year: 1989 },
  { artist: "Laura Branigan", title: "Self Control", year: 1984 },
  { artist: "Bruce Springsteen", title: "Dancing In the Dark", year: 1984 },
  { artist: "Sergio Dalma", title: "Bailar Pegados", year: 1991 },
  { artist: "Melendi", title: "Caminando por la vida", year: 2005 },
  { artist: "TOTO", title: "Africa", year: 1982 },
  { artist: "Fine Young Cannibals", title: "She Drives Me Crazy", year: 1988 },
  { artist: "Demarco Flamenco", title: "La Isla del Amor", year: 2017 },
  { artist: "Sam Cooke", title: "(What A) Wonderful World", year: 1960 },
  { artist: "Carlos Vives", title: "La Bicicleta", year: 2017 },
  { artist: "Alessia Cara", title: "Scars To Your Beautiful", year: 2016 },
  { artist: "Luis Aguile", title: "Dile", year: 2008 },
  { artist: "Carly Rae Jepsen", title: "Call Me Maybe", year: 2012 },
  { artist: "Laura Pausini", title: "Se fué", year: 1994 },
  { artist: "Oasis", title: "Wonderwall", year: 1995 },
  { artist: "Sia", title: "Cheap Thrills", year: 2016 },
  { artist: "Rick James", title: "Super Freak", year: 1981 },
  { artist: "Outkast", title: "Hey Ya!", year: 2003 },
  { artist: "Billy Swan", title: "I Can Help", year: 1974 },
  { artist: "Carlos Baute", title: "Colgando en tus manos (con Marta Sánchez)", year: 2009 },
  { artist: "Los Bravos", title: "Black is Black", year: 1966 },
  { artist: "Sister Sledge", title: "We Are Family", year: 1979 },
  { artist: "Cecilia", title: "Un Ramito de Violetas", year: 2013 },
  { artist: "Jeanette", title: "Soy rebelde", year: 2011 },
  { artist: "Umberto Tozzi", title: "Gloria", year: 1979 },
  { artist: "Bill Medley", title: "(I've Had) The Time of My Life", year: 1987 },
  { artist: "Kool & The Gang", title: "Celebration", year: 1980 },
  { artist: "Tears For Fears", title: "Shout", year: 1985 },
  { artist: "Billie Eilish", title: "bad guy", year: 2019 },
  { artist: "R.E.M.", title: "Everybody Hurts", year: 1992 },
  { artist: "Duo Dinamico", title: "Resistiré", year: 1988 },
  { artist: "Tequila", title: "Dime Que Me Quieres", year: 1980 },
  { artist: "Manolo Garcia", title: "Pajaros de Barro", year: 1998 },
  { artist: "Percy Sledge", title: "When a Man Loves a Woman", year: 1966 },
  { artist: "Amaral", title: "Marta, Sebas, Guille y los demás", year: 2005 },
  { artist: "Nino Bravo", title: "Libre", year: 1972 },
  { artist: "The Verve", title: "Bitter Sweet Symphony", year: 1997 },
  { artist: "Whitney Houston", title: "I Wanna Dance with Somebody (Who Loves Me)", year: 1987 },
  { artist: "El Canto Del Loco", title: "Zapatillas", year: 2005 },
  { artist: "Joseito Fernández", title: "Guajira Guantanamera", year: 2012 },
  { artist: "J Balvin", title: "Mi Gente", year: 2018 },
  { artist: "Shakira", title: "Waka Waka (This Time for Africa)", year: 2010 },
  { artist: "Bonnie Tyler", title: "It's a Heartache", year: 1977 },
  { artist: "Palito Ortega", title: "La Felicidad", year: 2001 },
  { artist: "Bebe", title: "Malo", year: 2003 },
  { artist: "Rednex", title: "Cotton Eye Joe", year: 1994 },
  { artist: "Miley Cyrus", title: "Wrecking Ball", year: 2013 },
  { artist: "Aqua", title: "Barbie Girl", year: 1997 },
  { artist: "Meghan Trainor", title: "All About That Bass", year: 2015 },
  { artist: "Los Diablos", title: "Un Rayo de Sol", year: 2013 },
  { artist: "Sonny & Cher", title: "I Got You Babe", year: 1965 },
  { artist: "Camilo Sesto", title: "Vivir Así Es Morir de Amor", year: 1978 },
  { artist: "Baccara", title: "Yes Sir, I Can Boogie", year: 1977 },
  { artist: "Enrique Iglesias", title: "Bailando", year: 2015 },
  { artist: "Owl City", title: "Fireflies", year: 2009 },
  { artist: "Christina Aguilera", title: "Genie In a Bottle", year: 1999 },
  { artist: "Tina Turner", title: "The Best", year: 1989 },
  { artist: "Céline Dion", title: "My Heart Will Go On", year: 1997 },
  { artist: "Kiko Veneno", title: "Volando Voy", year: 1992 },
  { artist: "Don Omar", title: "Danza Kuduro", year: 2011 },
  { artist: "Katy Perry", title: "Firework", year: 2010 },
  { artist: "Amii Stewart", title: "Knock On Wood", year: 2012 },
  { artist: "Hermanas Fleta", title: "Chacachá del tren", year: 2005 },
  { artist: "Yazoo", title: "Don't Go", year: 1982 },
  { artist: "Enrico Caruso", title: "Rigoletto: \"La Donna E' Mobile\"", year: 2011 },
  { artist: "Luis Fonsi", title: "Despacito", year: 2019 },
  { artist: "Nirvana", title: "Smells Like Teen Spirit", year: 1991 },
  { artist: "Rocío Dúrcal", title: "Me Gustas Mucho", year: 1992 },
  { artist: "Raffaela Carrá", title: "Hay que venir al sur", year: 2013 },
  { artist: "The Kinks", title: "Lola", year: 1970 },
  { artist: "Daddy Yankee", title: "Lo Que Pasó, Pasó", year: 2004 },
  { artist: "Glenn Miller", title: "In the Mood", year: 1939 },
  { artist: "Miguel Bosé", title: "Amante Bandido", year: 1984 },
  { artist: "The Chainsmokers", title: "Closer", year: 2016 },
  { artist: "Bob Sinclar", title: "World Hold on (Children of the Sky)", year: 2006 },
  { artist: "Reel 2 Real", title: "I Like To Move It", year: 1994 },
  { artist: "Pablo López", title: "Tu Enemigo", year: 2015 },
  { artist: "The Cure", title: "Friday I'm In Love", year: 1992 },
  { artist: "Antonio Machín", title: "Tengo una Debilidad", year: 2012 },
  { artist: "Tequila", title: "Salta!!!", year: 1981 },
  { artist: "Luz Casal", title: "No me importa nada", year: 1989 },
  { artist: "Limahl", title: "Never Ending Story", year: 1984 },
  { artist: "Manolo Escobar", title: "Mi Carro", year: 1991 },
  { artist: "The Refrescos", title: "Aquí No Hay Playa", year: 1989 },
  { artist: "Lenny Kravitz", title: "Fly Away", year: 1998 },
  { artist: "Ace of Base", title: "All That She Wants", year: 1993 },
  { artist: "Major Lazer", title: "Lean On", year: 2015 },
  { artist: "The Cardigans", title: "Lovefool", year: 1996 },
  { artist: "Raphael", title: "Mi gran noche", year: 1967 },
  { artist: "La Casa Azul", title: "La Revolución Sexual", year: 2007 },
  { artist: "Irene Cara", title: "Flashdance...What a Feeling", year: 1983 },
  { artist: "Vanessa Carlton", title: "A Thousand Miles", year: 2002 },
  { artist: "Radio Futura", title: "Veneno en la Piel", year: 1990 },
  { artist: "Antonio Molina", title: "Soy minero", year: 1996 },
  { artist: "Burning", title: "Que Hace una Chica Como Tu en un Sitio Como Este", year: 2013 },
  { artist: "Los Del Rio", title: "Macarena", year: 1993 },
  { artist: "Boston", title: "More Than a Feeling", year: 1976 },
  { artist: "Mecano", title: "Me cuesta tanto olvidarte", year: 1986 },
  { artist: "Los Tres Caballeros", title: "El Reloj", year: 1994 },
  { artist: "Conchita Velasco", title: "Chica YeYe", year: 1965 },
  { artist: "Drake", title: "Toosie Slide", year: 2020 },
  { artist: "Wiz Khalifa", title: "See You Again", year: 2015 },
  { artist: "Elvis Presley", title: "Jailhouse Rock", year: 1958 },
  { artist: "ROSALÍA", title: "MALAMENTE", year: 2018 },
  { artist: "Chubby Checker", title: "The Twist", year: 1962 },
  { artist: "Juanes", title: "La Camisa Negra", year: 2004 },
  { artist: "Manuel Carrasco", title: "Que Nadie", year: 2009 },
  { artist: "Formula V", title: "Cuéntame", year: 1969 },
  { artist: "James Brown & The Famous Flames", title: "I Got You (I Feel Good)", year: 1966 },
  { artist: "Efecto Pasillo", title: "Cuando me siento bien", year: 2015 },
  { artist: "Duffy", title: "Mercy", year: 2008 },
  { artist: "Karina", title: "El baúl de los recuerdos", year: 1970 },
  { artist: "Bruno Mars", title: "The Lazy Song", year: 2010 },
  { artist: "Conchita Bautista", title: "Estando Contigo", year: 1961 },
  { artist: "Ana Belén", title: "La Puerta de Alcalá", year: 1986 },
  { artist: "Britney Spears", title: "Oops!...I Did It Again", year: 2000 },
  { artist: "Jimmy Cliff", title: "You Can Get It If You Really Want", year: 1970 },
  { artist: "Bon Jovi", title: "It's My Life", year: 2000 },
  { artist: "Tino Casal", title: "Eloise", year: 1987 },
  { artist: "José Luis Perales", title: "¿Y Cómo Es Él?", year: 1982 },
  { artist: "Eric Prydz", title: "Call on Me", year: 2004 },
  { artist: "La Oreja de Van Gogh", title: "Rosas", year: 2003 },
  { artist: "Madonna", title: "Like a Prayer", year: 1989 },
  { artist: "Maná", title: "Vivir Sin Aire", year: 1992 },
  { artist: "Fugees", title: "Killing Me Softly With His Song", year: 1996 },
  { artist: "Alaska Y Los Pegamoides", title: "Bailando", year: 1982 },
  { artist: "Maria Becerra", title: "High (Remix)", year: 2020 },
  { artist: "Richard Marx", title: "Right Here Waiting", year: 1989 },
  { artist: "Ole Ole", title: "No Controles", year: 1983 },
  { artist: "Pont Aeri", title: "Flying Free", year: 1999 },
  { artist: "Daft Punk", title: "One More Time", year: 2000 },
  { artist: "Lou Bega", title: "Mambo No. 5 (a Little Bit of...)", year: 1999 },
  { artist: "Emilio Tuero", title: "Bésame Mucho", year: 2014 },
  { artist: "La Mosca", title: "Para No Verte Más", year: 2000 },
  { artist: "The Beach Boys", title: "Surfin' U.S.A. (Mono)", year: 1963 },
  { artist: "Domenico Modugno", title: "Nel Blu Dipinto Di Blu", year: 1958 },
  { artist: "Bad Bunny", title: "DÁKITI", year: 2020 },
  { artist: "C. Tangana", title: "Tú Me Dejaste De Querer", year: 2021 },
  { artist: "Marc Anthony", title: "Vivir Mi Vida", year: 2013 },
  { artist: "Rihanna", title: "Work", year: 2016 },
  { artist: "Monica Naranjo", title: "Sobreviviré", year: 2000 },
  { artist: "M-Clan", title: "Carolina", year: 1999 },
  { artist: "Thelma Houston", title: "Don't Leave Me This Way", year: 1976 },
  { artist: "The Trammps", title: "Disco Inferno", year: 1976 },
  { artist: "Juan Magán", title: "Usted", year: 2018 },
  { artist: "Natalie Imbruglia", title: "Torn", year: 1997 },
  { artist: "Eddy Grant", title: "Gimme Hope Jo'Anna", year: 1988 },
  { artist: "Billy Joel", title: "Piano Man", year: 1973 },
  { artist: "The Beatles", title: "Get Back", year: 1970 },
  { artist: "Mocedades", title: "Eres Tú", year: 1973 },
  { artist: "Patrick Hernandez", title: "Born to Be Alive", year: 1978 },
  { artist: "Hombres G", title: "Devuélveme a mi chica", year: 1985 },
  { artist: "Culture Club", title: "Karma Chameleon", year: 1983 },
  { artist: "The Bangles", title: "Walk Like an Egyptian", year: 1986 },
  { artist: "The Supremes", title: "You Can't Hurry Love", year: 1966 },
  { artist: "Nena Daconte", title: "Tenía Tanto Que Darte", year: 2008 },
  { artist: "Mano Negra", title: "Mala Vida", year: 1988 },
  { artist: "Coolio", title: "Gangsta's Paradise", year: 1995 },
  { artist: "Loreen", title: "Euphoria", year: 2012 },
  { artist: "Macaco", title: "Moving", year: 2009 },
  { artist: "Freddie Mercury", title: "Barcelona", year: 1987 },
  { artist: "Boney M.", title: "Daddy Cool", year: 1976 },
  { artist: "Maroon 5", title: "Moves Like Jagger", year: 2011 },
  { artist: "Bob Marley & The Wailers", title: "No Woman No Cry", year: 1974 },
  { artist: "Las Grecas", title: "Te Estoy Amando Locamente", year: 1974 },
  { artist: "Shawn Mendes", title: "Señorita", year: 2019 },
  { artist: "Cher", title: "Believe", year: 1998 },
  { artist: "Beyoncé", title: "Crazy In Love", year: 2003 },
  { artist: "Nancys Rubias", title: "Me encanta", year: 2013 },
  { artist: "LMFAO", title: "Party Rock Anthem", year: 2011 },
  { artist: "Ska-P", title: "Cannabis", year: 1996 },
  { artist: "Maldita Nerea", title: "El Secreto de las Tortugas", year: 2009 },
  { artist: "OneRepublic", title: "Counting Stars", year: 2013 },
  { artist: "Heroes Del Silencio", title: "Entre dos tierras", year: 1990 },
  { artist: "Depeche Mode", title: "Enjoy the Silence", year: 1990 },
  { artist: "Coldplay", title: "Talk", year: 2005 },
  { artist: "Alicia Keys", title: "Fallin'", year: 2001 },
  { artist: "Massiel", title: "La, La, La", year: 1968 },
  { artist: "Manfred Mann", title: "Do Wah Diddy Diddy", year: 1964 },
  { artist: "Los Secretos", title: "Pero a tu lado", year: 1995 },
  { artist: "Red Hot Chili Peppers", title: "Under the Bridge", year: 1991 },
  { artist: "John Legend", title: "All of Me", year: 2013 },
  { artist: "Gente De Zona", title: "La Gozadera", year: 2016 },
  { artist: "Don Omar", title: "Dale Don Dale", year: 2003 },
  { artist: "Pablo Alborán", title: "Te he echado de menos", year: 2011 },
  { artist: "David Bisbal", title: "Ave María", year: 2002 },
  { artist: "Alvaro Soler", title: "Sofia", year: 2016 },
  { artist: "Mecano", title: "Me Colé en una Fiesta", year: 1988 },
  { artist: "The Champs", title: "Tequila", year: 1958 },
  { artist: "Wet Wet Wet", title: "Love Is All Around", year: 1995 },
  { artist: "The Police", title: "Every Breath You Take", year: 1983 },
  { artist: "Taburete", title: "Sirenas", year: 2016 },
  { artist: "Danza Invisible", title: "Sabor de amor", year: 1988 },
  { artist: "Dire Straits", title: "Walk Of Life", year: 1985 },
  { artist: "Enrique Iglesias", title: "DUELE EL CORAZON", year: 2016 },
  { artist: "Little Eva", title: "The Locomotion", year: 1962 },
  { artist: "Jarabe De Palo", title: "La flaca", year: 1996 },
  { artist: "Alejandro Sanz", title: "Corazón partío", year: 1997 },
  { artist: "Bill Haley & His Comets", title: "See You Later, Alligator", year: 1956 },
  { artist: "The Cranberries", title: "Zombie", year: 1994 },
  { artist: "Joaquín Sabina", title: "Y Nos Dieron las Diez", year: 1992 },
  { artist: "Estopa", title: "Como Camarón", year: 1999 },
  { artist: "Shakira", title: "Las de la Intuición", year: 2005 },
  { artist: "Coti", title: "Nada Fue Un Error", year: 2003 },
  { artist: "Alex Y Christina", title: "¡Chas! Y aparezco a tu lado", year: 1988 },
  { artist: "George Harrison", title: "Got My Mind Set On You", year: 1988 },
  { artist: "Ricky Martin", title: "María", year: 1995 },
  { artist: "Azucar Moreno", title: "Sólo Se Vive una Vez", year: 1997 },
  { artist: "Lynyrd Skynyrd", title: "Sweet Home Alabama", year: 1974 },
  { artist: "Alaska Y Dinarama", title: "Ni tú ni nadie", year: 1984 },
  { artist: "Lady Gaga", title: "Poker Face", year: 2008 },
  { artist: "Los Brincos", title: "Flamenco", year: 1964 },
  { artist: "Snow", title: "Informer", year: 1993 },
  { artist: "Raul", title: "Sueño Su Boca", year: 2001 },
  { artist: "Modern Talking", title: "Brother Louie", year: 1986 },
  { artist: "Roy Orbison", title: "Oh, Pretty Woman", year: 1964 },
  { artist: "Los Bravos", title: "Los Chicos Con las Chicas", year: 1967 },
  { artist: "La Pegatina", title: "Lloverá y yo veré", year: 2013 },
  { artist: "Lola Flores", title: "A Tu Vera", year: 1991 },
  { artist: "Marta Sánchez", title: "Desesperada", year: 1993 },
  { artist: "MIKA", title: "Relax, Take It Easy", year: 2006 },
  { artist: "Los Secretos", title: "Déjame", year: 1981 },
  { artist: "Enya", title: "Orinoco Flow", year: 1988 },
  { artist: "Diana Ross", title: "Upside Down", year: 1980 },
  { artist: "Adele", title: "Rolling in the Deep", year: 2011 },
  { artist: "Nacha Pop", title: "Chica de ayer", year: 1980 },
  { artist: "Carly Simon", title: "You're So Vain", year: 1972 },
  { artist: "No Doubt", title: "Don't Speak", year: 1995 },
  { artist: "Betty Everett", title: "It's In The Kiss (The Shoop Shoop Song)", year: 1964 },
  { artist: "Roxette", title: "Joyride", year: 1991 },
  { artist: "Paulina Rubio", title: "Ni Una Sola Palabra", year: 2006 },
  { artist: "Daryl Hall & John Oates", title: "Maneater", year: 1982 },
  { artist: "Las Ketchup", title: "The Ketchup Song (Aserejé)", year: 2002 },
  { artist: "Ana Maria", title: "Campanera", year: 1993 },
  { artist: "Amy Winehouse", title: "Rehab", year: 2006 },
  { artist: "Aitana", title: "11 RAZONES", year: 2020 },
  { artist: "Elvis Presley", title: "Can't Help Falling in Love", year: 1961 },
  { artist: "Toploader", title: "Dancing in the Moonlight", year: 2000 },
  { artist: "Gipsy Kings", title: "Bamboléo", year: 1987 },
  { artist: "Manu Chao", title: "Me Gustas Tu", year: 2001 },
  { artist: "Pimpinela", title: "Olvídame y Pega la Vuelta", year: 1982 },
  { artist: "Dua Lipa", title: "Break My Heart", year: 2020 },
  { artist: "Don Patricio", title: "Contando Lunares", year: 2019 },
  { artist: "Aretha Franklin", title: "Respect", year: 1967 },
  { artist: "Los Rodriguez", title: "Sin documentos", year: 1993 },
  { artist: "Ed Sheeran", title: "Shape of You", year: 2017 },
  { artist: "The Rolling Stones", title: "Start Me Up", year: 1981 },
  { artist: "Calle 13", title: "Atrévete-Te-Te", year: 2005 },
  { artist: "David Bowie", title: "Space Oddity", year: 1969 },
  { artist: "Lola Flores", title: "Pena Penita Pena", year: 1991 },
  { artist: "Haddaway", title: "What Is Love", year: 1993 },
  { artist: "Mägo de Oz", title: "Fiesta Pagana", year: 2000 },
  { artist: "Lolita", title: "Sarandonga", year: 2001 },
  { artist: "Loquillo", title: "Cadillac solitario", year: 1984 },
  { artist: "Pereza", title: "Princesas", year: 2005 },
  { artist: "Robbie Williams", title: "Feel", year: 2002 },
  { artist: "Ana Guerra", title: "Ni La Hora", year: 2018 },
  { artist: "Los Sirex", title: "La Escoba", year: 1964 },
  { artist: "Salvatore Adamo", title: "Mis Manos en Tu Cintura", year: 1995 },
  { artist: "Avril Lavigne", title: "Girlfriend", year: 2007 },
  { artist: "Rocío Jurado", title: "Como una Ola", year: 1981 },
  { artist: "Tony Ronald", title: "Help, áyudame", year: 1971 },
  { artist: "Cliff Richard", title: "Congratulations", year: 1968 },
  { artist: "Gloria Gaynor", title: "I Will Survive", year: 1978 },
  { artist: "ABBA", title: "Waterloo", year: 1974 },
  { artist: "O-Zone", title: "Dragostea Din Tei", year: 2004 },
  { artist: "Jorge Sepúlveda", title: "Tres Veces Guapa", year: 2015 },
  { artist: "Paul McCartney", title: "Live And Let Die", year: 1973 },
  { artist: "Barry White", title: "You're The First, The Last, My Everything", year: 1974 },
  { artist: "Joan Manuel Serrat", title: "Mediterraneo", year: 1971 },
  { artist: "The Weeknd", title: "Blinding Lights", year: 2020 },
  { artist: "Avicii", title: "Without You", year: 2017 },
  { artist: "Mungo Jerry", title: "In the Summertime", year: 1970 },
  { artist: "PSY", title: "Gangnam Style (강남스타일)", year: 2012 },
  { artist: "Julio Iglesias", title: "Soy un Truhán, Soy un Señor", year: 1978 },
  { artist: "Amy Macdonald", title: "This Is The Life", year: 2007 },
  { artist: "Seguridad Social", title: "Chiquilla", year: 1991 },
  { artist: "Plastic Bertrand", title: "Ca plane pour moi", year: 1977 },
  { artist: "Tones And I", title: "Dance Monkey", year: 2019 },
  { artist: "Calvin Harris", title: "Promises", year: 2018 },
  { artist: "Camila Cabello", title: "Havana", year: 2018 },
  { artist: "Bongo Botrako", title: "Todos los días sale el sol", year: 2010 },
  { artist: "Cali Y El Dandee", title: "Yo Te Esperaré", year: 2012 },
  { artist: "Marisol", title: "Tombola", year: 1962 },
  { artist: "Nelly Furtado", title: "Say It Right", year: 2006 },
  { artist: "Salomé", title: "Vivo Cantando", year: 1969 },
  { artist: "Raffaella Carrà", title: "En el Amor Todo Es Empezar (A far l'amore comincia tu)", year: 1976 },
  { artist: "Nickelback", title: "How You Remind Me", year: 2001 },
  { artist: "Los Chunguitos", title: "Me Quedo Contigo", year: 1982 },
  { artist: "Maluma", title: "Felices los 4", year: 2018 },
  { artist: "Nancy Sinatra", title: "These Boots Are Made For Walkin'", year: 1966 },
  { artist: "Ritchie Valens", title: "La Bamba", year: 1959 },
  { artist: "Peret", title: "Canta y Sé Feliz", year: 2001 },
  { artist: "Steppenwolf", title: "Born To Be Wild", year: 1968 },
  { artist: "Formula V", title: "Eva Maria", year: 1985 },
  { artist: "Erma Franklin", title: "Piece of My Heart", year: 1967 },
  { artist: "Gotye", title: "Somebody That I Used To Know", year: 2011 }
];
